logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/babap
    username: root
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: create
  mail:
    senderEmail: huipulci1@naver.com
    host: smtp.naver.com
    port: 465
    username: huipulci1
    password: dbruaqudtls123@
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            enable: true


swagger:
  server-url: http://54.80.162.117:8080

cors:
  allowedOrigins: http://localhost:3000

token:
  secretKey: "dwqcj120fj0c01jtlk13490013j0412j0921309850913j0d09aucsacjas0921u3091rjlkasud8921nkcl9012u093kld13202145fdsaqas9"
  accessTokenExpirationDays: 20000
