logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

    hibernate:
      ddl-auto: create
  mail:
    senderEmail: 보내는 사람 이메일 주소
    host: smtp.naver.com
    port: 465
    username: 네이버 아이디
    password: 네이버 비번
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            enable: true


swagger:
  server-url: http://localhost:8080

cors:
  allowedOrigins: http://localhost:3000

token:
  secretKey: "dwqcj120fj0c01jtlk13490013j0412j0921309850913j0d09aucsacjas0921u3091rjlkasud8921nkcl9012u093kld13202145fdsaqas9"
  accessTokenExpirationDays: 2000
